apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: r208vdsb0-go 
  janus-idp.io/tekton: r208vdsb0-go
  backstage.io/kubernetes-id: r208vdsb0-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: r208vdsb0-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  